### ISSUE TITLE
Show confirmation modal when user reloads page.

### ISSUE THREAD

**Issue by AdityaHirapara** [wdlsvnit/Omeclone#124]
**Current behaviour**
Chat ends without confirmation when user reloads page.

**Expected behaviour**
Confirmation modal should be shown on reloading of page.

**Comment by ajayns** [comment]
Rather than a confirmation modal, shouldn't it remain on the same chat if the user reloads? In case user navigates back or so then it's required to a show an alert.

**Comment by sumedh123** [comment]
To keep the user on the same page, we need to store the messages, right?
Because we aren't using any backend stuff here, we need to figure out
something.

**Comment by ajayns** [comment]
Storing messages is not a good option. So I'd say we'll just have to go with an alert in case the user decides to do any navigation at all or hits refresh. 

@AdityaHirapara The `window.onbeforeunload` event can be used to define a function with calls when user. I'm not sure about browser compatibility though.

**Comment by AdityaHirapara** [comment]
@ajayns ```windows.onbeforeunload``` is not even compatible with chrome, So we can't use it.

**Comment by AdityaHirapara** [comment]
@sumedh123 In form, when we send message, it will reload page and chat will end.

**Comment by sumedh123** [comment]
we can prevent the default action right? @AdityaHirapa.

**Comment by AdityaHirapara** [comment]
@sumedh123, Then it will prevent that alert too

**Comment by ajayns** [comment]
@AdityaHirapara `preventDefault()` does that?

And chrome for me seems to show "Do you want to leave this site" irrespective of return message we put in the function. Isn't that fine for now? (Talking about `onbeforeload` here)

**Comment by sumedh123** [comment]
Yeah we need a MVP(Minimum viable product) for now.

**Comment by sumedh123** [comment]
For now, it's better to have something than nothing. Let's implement the discussed one then.
