### ISSUE TITLE
Propose some color schemes and themes for the templates.

### ISSUE THREAD

**Issue by sumedh123** [wdlsvnit/Omeclone#18]
Currently we dont have uniform colors throughout the app. Please propose some color schemes.

**Comment by littlestar642** [comment]
![img](https://user-images.githubusercontent.com/28615945/35009408-6f0187f8-fb25-11e7-8e84-db229d0862a4.png)

How about this for -: (left to right)

#DB3340 - for Header bar,
#E8B71A - for Subheadings,
#F7EAC8 - for background,
#1FDA9A - for user chatbox,
#28ABE3 - for another user chatbox

**Comment by mrmir** [comment]
How about a light grey for the background, instead? Something like #b3b3b3?

**Comment by sumedh123** [comment]
Can anyone show me both of the pages implemented in the scheme?

**Comment by littlestar642** [comment]
Yes i will be showing one implemented.

**Comment by littlestar642** [comment]
https://boiling-castle-60412.herokuapp.com/chat
This is a link to the prototype

**Comment by sumedh123** [comment]
@littlestar642 any updates on this?

**Comment by mrmir** [comment]
I'll take it up, expect a PR by tomorrow evening!

**Comment by sumedh123** [comment]
@mrmir Go ahead.
