### ISSUE TITLE
Chat page template with mock data.

### ISSUE THREAD

**Issue by sumedh123** [wdlsvnit/Omeclone#3]
Please design and implement a chat page template. Have a good one.

**Comment by sumedh123** [comment]
Things to be doen:
- Implement the whole page
- Have some mock data in it.
- hitting enter should append the data in the text input to the chat window

Use the semantic ui cdn for now. Later we ll shift to the installation of semantic ui through npm when issue #4 resolves.

**Comment by littlestar642** [comment]
Hey.I want to work on this issue.

**Comment by sumedh123** [comment]
@littlestar642 Any ETA?
