### ISSUE TITLE
Change the source of the scripts loaded from cdn to bower components.

### ISSUE THREAD

**Issue by sumedh123** [wdlsvnit/Omeclone#30]
Use the bower components instead of scripts loaded through cdn.

**Comment by littlestar642** [comment]
I want to work on this.

**Comment by sumedh123** [comment]
@littlestar642 After you solve the color scheme issue.

**Comment by littlestar642** [comment]
Sure 😄 @sumedh123

**Comment by therohitramesh** [comment]
I'd like to work on this.

**Comment by sumedh123** [comment]
@therohitramesh any updates on this?

**Comment by therohitramesh** [comment]
@sumedh123 The problem still persists. I'll work with @AdityaHirapara and fix it.
