### ISSUE TITLE
Add a feature of changing background color as per user's choice.

### ISSUE THREAD

**Issue by jainkeval** [wdlsvnit/Omeclone#37]
We will provide an option by which user may choose the background color.
Further we can extend this to changing the background color for the next person in the chat room

**Comment by sumedh123** [comment]
Seems an invalid issue. I mean why would the user want to change the background? I want input from others. @kvnamipara

**Comment by littlestar642** [comment]
This is a feature similar to what mesenger too provides.Here we aim at making two strangers talk.A user would not be intersted in changing the color theme of someone he is talking to

**Comment by jainkeval** [comment]
@sumedh123 @kvnamipara shall I close this issue?
