### ISSUE TITLE
Send button of the chat page is overflowing on mobile

### ISSUE THREAD

**Issue by jainkeval** [wdlsvnit/Omeclone#38]
It is expected that the send button should be in a proper position in mobile as well as desktop mode.
![image](https://user-images.githubusercontent.com/26284185/35378107-98bc5c18-01d7-11e8-9b23-c7117afc78a0.png)

**Comment by jairoMolina9** [comment]
You will need to create parameters, please provide more information on how you developing this, what software, what language?

Thank you.

**Comment by jainkeval** [comment]
It will look better if only symbols show in the mobile

**Comment by sumedh123** [comment]
@jairoMolina9 We are using semantic ui framework and for this issue we ll be changing the classes to show only icons on small screens.
