### ISSUE TITLE
Make the landing page good to look.

### ISSUE THREAD

**Issue by sumedh123** [wdlsvnit/Omeclone#43]
Currently we just have a vague implementation of our landing page.
<img width="1440" alt="screen shot 2018-01-30 at 6 20 17 pm" src="https://user-images.githubusercontent.com/17925669/35567207-42da6e54-05ea-11e8-87aa-3360ea7111c1.png">

Please propose a good implementation.

**Comment by mrmir** [comment]
Can I work on this, or is Avinash doing so?

**Comment by sumedh123** [comment]
@littlestar642 ^^

**Comment by littlestar642** [comment]
@mrmir Yup.I am developing this right now :smile
