### ISSUE TITLE
On hitting enter the messages should be sent

### ISSUE THREAD

**Issue by littlestar642** [wdlsvnit/Omeclone#52]
*Presently,the message sending button is not responding on hitting enter on the keyboard.*

**Comment by sumedh123** [comment]
Make it a form. And add action submit to the button.

**Comment by jainkeval** [comment]
Is this issue open to be worked upon?

**Comment by sumedh123** [comment]
@jainkeval yes

**Comment by jainkeval** [comment]
I will do this

**Comment by littlestar642** [comment]
Sure @jainkeval .Just ensure that the new html being appended is having a bottom and top margin of 1px so that every individual message looks seperated.

**Comment by jainkeval** [comment]
@littlestar642 I have already done it, check it out! :smile:
