### ISSUE TITLE
scroll up as new message arrived

### ISSUE THREAD

**Issue by kvnamipara** [wdlsvnit/Omeclone#55]
when chat messages are going out of viewport, we should scroll up and append messages at the bottom.

**Comment by kvnamipara** [comment]
![screen shot 2018-02-04 at 12 39 04 am](https://user-images.githubusercontent.com/18012563/35770569-dc2ed1e2-0943-11e8-9463-17162e7d3654.png)

Message is hidden behind input field, this should not happen

**Comment by AdityaHirapara** [comment]
I will fix this.
