### ISSUE TITLE
show time on each chat message

### ISSUE THREAD

**Issue by kvnamipara** [wdlsvnit/Omeclone#56]
Show the time of posting at each message thread when message is sent

**Comment by littlestar642** [comment]
these can only be done once #51 gets merged. Isnt it?

**Comment by littlestar642** [comment]
I will like to work on this.

**Comment by kvnamipara** [comment]
@littlestar642 #51 is merged.

**Comment by jainkeval** [comment]
@littlestar642 are you working on this issue?

**Comment by littlestar642** [comment]
Yes. I will be making a pr soon
