### ISSUE TITLE
random username assignment

### ISSUE THREAD

**Issue by kvnamipara** [wdlsvnit/Omeclone#57]
Assign random username to users when they join for chat

**Comment by jainkeval** [comment]
I would like to work on this

**Comment by AdityaHirapara** [comment]
Or we can tell them to enter nick name for chat, @kvnamipara @jainkeval

**Comment by kvnamipara** [comment]
yes we can ask user to enter username
so we will keep placeholder as random username and then if user wants to modify they can
we will ask username before entering chat room

@sumedh123 what do you think about this feature !!
is it user-friendly to ask username before each time?

**Comment by sumedh123** [comment]
nope. users can reveal identity

**Comment by sumedh123** [comment]
what's the point if we are giving them chance to set their own username. they ll set up their name. not good for us. lost purpose of app. generate random ones.
