### ISSUE TITLE
kick out the user if inactive for long time

### ISSUE THREAD

**Issue by kvnamipara** [wdlsvnit/Omeclone#58]
we have to end the conversation if one of user if not responding 
we can set certain time limit and make this possible

Please share your views

**Comment by sumedh123** [comment]
Lets make it 4-5 mins because it will continuously make ajax calls to socketio. and that's not good for us.

**Comment by kvnamipara** [comment]
@sumedh123  cant's we make a different ajax calls once user has not typed something in typing field in specified times?

**Comment by sumedh123** [comment]
sockeito basically oepns up a long polling and hence requests are continuously sent. see console.

**Comment by sumedh123** [comment]
@kvnamipara 'cant's we make a different ajax calls once user has not typed something in typing field in specified times?' 

Please explain in detail. dint get it.

**Comment by jainkeval** [comment]
I would like to work on this.

**Comment by kvnamipara** [comment]
@sumedh123 @jainkeval we should limit this to 1 minute as sole purpose of user will be to chat

**Comment by sumedh123** [comment]
@jainkeval Are you doing this one or https://github.com/wdlsvnit/Omeclone/issues/78 ?
