### ISSUE TITLE
Encrypt the chats.

### ISSUE THREAD

**Issue by sumedh123** [wdlsvnit/Omeclone#81]
This is one of the most important feature that our app should have. We need to provide end to end encryption. Propose your ideas how you want to do this.

**Comment by therohitramesh** [comment]
How about this package? It's called [cryptalk](https://www.npmjs.com/package/cryptalk).

**Comment by sumedh123** [comment]
@therohitramesh seems it is whole encrypted chat application. There is one more cryptico.

**Comment by therohitramesh** [comment]
Oh yes, @sumedh123 that's right it is an application by itself. I went through cryptico's documentation. It looks good.

**Comment by jainkeval** [comment]
I would like to work on this.

**Comment by therohitramesh** [comment]
@jainkeval Have you already started working on this?

**Comment by sumedh123** [comment]
@therohitramesh give it a try.

**Comment by sumedh123** [comment]
@therohitramesh seems away. Assigning this to @AdityaHirapara
