### ISSUE TITLE
Show user connection or disconnection message on chat page

### ISSUE THREAD

**Issue by AdityaHirapara** [wdlsvnit/Omeclone#92]
Display message when any of user gets connected or disconnected on chat page.

**Comment by mrmir** [comment]
> Display message when any of user gets connected or disconnected on chat page.

Can you elaborate, please? Do you mean that in the chat page there should be a message saying "New user has been connected", or do you mean something else?

**Comment by sumedh123** [comment]
Display all the messages using toast.
